import { Lang, UIStrings } from "./types";

export const uiStrings: Record<Lang, UIStrings> = {
  ar: {
    semesterStart: "بداية الفصل الدراسي:",
    semesterEnd: "نهاية الفصل الدراسي:",
    drivingTimeTo: "الوقت للوصول للجامعة:",
    drivingTimeFrom: "الوقت للعودة للمنزل:",
    hoursPlaceholder: "ساعة",
    minutesPlaceholder: "دقيقة",
    drivingEmoji: "إيموجي القيادة:",
    downloadIcs: "تحميل ICS",
    downloadTampermonkey: "تحميل سكريبت تمبرمانكي",
    syncGoogleCalendar: "مزامنة مع تقويم Google",
    syncGoogleUnavailable: "أضف VITE_GOOGLE_CLIENT_ID لتفعيل مزامنة Google.",
    syncGoogleWorking: "جاري المزامنة مع Google Calendar...",
    syncGoogleDone: "اكتملت المزامنة: تم حذف {deleted} وإضافة {inserted} حدث.",
    syncGoogleFailed: "فشلت المزامنة مع Google Calendar.",
    guide: "دليل",
    reset: "إعادة تعيين",
    language: "English",
    alertDates: "الرجاء تحديد تاريخ بداية ونهاية الفصل الدراسي أولاً.",
    alertTable: "جدول المواد الدراسية غير موجود!",
    guideTitle: "دليل الاستخدام",
    guideStep1: "1. افتح https://eserve.psau.edu.sa/ku/ui/student/homeIndex.faces وسجّل الدخول.",
    guideStep2: "2. اذهب إلى صفحة 'المقررات المسجلة'.",
    guideStep3: "3. اضغط Ctrl+S (أو كلك يمين > حفظ باسم) واحفظ الصفحة كملف HTML.",
    guideStep4: "4. ارفع ملف HTML هنا في SchMaker.",
    guideStep5: "5. عدّل الإعدادات ثم نزّل ICS أو استخدم المزامنة مع Google.",
    guideClose: "إغلاق",
    drivingTo: "القيادة إلى الجامعة",
    drivingFrom: "العودة للمنزل",
    ramadanSchedule: "جدول رمضان:",
    ramadanOff: "بدون تعديل",
    ramadanEngineering: "جميع الكليات",
    ramadanFirstYear: "السنة التحضيرية",
    uploadTitle: "ارفع ملف الجدول (HTML)",
    uploadHint: "افتح صفحة المقررات المسجلة ثم احفظها HTML وارفعها هنا.",
    uploadButton: "اختيار ملف HTML",
    uploadInvalid: "الملف لا يحتوي على جدول صالح.",
    selectedFile: "الملف المحدد:",
    noFile: "لم يتم اختيار ملف",
    generatePreview: "تحليل الجدول",
    themeTitle: "الجدول إلى التقويم",
    settingsTitle: "الإعدادات",
    previewTitle: "المعاينة",
    previewEmptyHint: "ارفع ملف الجدول HTML لعرض المعاينة.",
  },
  en: {
    semesterStart: "Semester Start:",
    semesterEnd: "Semester End:",
    drivingTimeTo: "Time to College:",
    drivingTimeFrom: "Time Back Home:",
    hoursPlaceholder: "Hours",
    minutesPlaceholder: "Mins",
    drivingEmoji: "Driving Emoji:",
    downloadIcs: "Download ICS",
    downloadTampermonkey: "Download Tampermonkey Script",
    syncGoogleCalendar: "Sync to Google Calendar",
    syncGoogleUnavailable: "Set VITE_GOOGLE_CLIENT_ID to enable Google sync.",
    syncGoogleWorking: "Syncing with Google Calendar...",
    syncGoogleDone: "Sync complete: deleted {deleted}, inserted {inserted} events.",
    syncGoogleFailed: "Google Calendar sync failed.",
    guide: "Guide",
    reset: "Reset",
    language: "العربية",
    alertDates: "Please select the semester start and end dates first.",
    alertTable: "Schedule table not found!",
    guideTitle: "How to Use",
    guideStep1: "1. Open https://eserve.psau.edu.sa/ku/ui/student/homeIndex.faces and sign in.",
    guideStep2: "2. Go to the 'Registered Courses' page (المقررات المسجلة).",
    guideStep3: "3. Press Ctrl+S (or right-click > Save as) and save the page as HTML.",
    guideStep4: "4. Upload that HTML file here in SchMaker.",
    guideStep5: "5. Adjust settings, then download ICS or sync to Google Calendar.",
    guideClose: "Close",
    drivingTo: "Driving to College",
    drivingFrom: "Driving Back Home",
    ramadanSchedule: "Ramadan Schedule:",
    ramadanOff: "No Ramadan Schedule",
    ramadanEngineering: "All Colleges",
    ramadanFirstYear: "1st Year",
    uploadTitle: "Upload Schedule HTML",
    uploadHint: "Open Registered Courses, save as HTML, then upload it here.",
    uploadButton: "Choose HTML File",
    uploadInvalid: "Uploaded file does not contain a valid schedule table.",
    selectedFile: "Selected file:",
    noFile: "No file selected",
    generatePreview: "Parse Schedule",
    themeTitle: "Schedule to Calendar",
    settingsTitle: "Settings",
    previewTitle: "Preview",
    previewEmptyHint: "Upload your schedule HTML to preview.",
  },
};
